// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlfBTLmVO0M3H3SeoYBBbDLMbTMhKmRXc',
    appId: '1:533186851590:web:d470da08aa37e90eba2487',
    messagingSenderId: '533186851590',
    projectId: 'siskang-cbf03',
    authDomain: 'siskang-cbf03.firebaseapp.com',
    storageBucket: 'siskang-cbf03.appspot.com',
    measurementId: 'G-BCRKP8NCVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmcFvA9aT8SM-OGT3ycdQL3w9W4u099c0',
    appId: '1:533186851590:android:df6a43cd26ac8617ba2487',
    messagingSenderId: '533186851590',
    projectId: 'siskang-cbf03',
    storageBucket: 'siskang-cbf03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1_75bhyEncX4bftW0XRWvJzbaaKFqWls',
    appId: '1:533186851590:ios:22168c688a399ea7ba2487',
    messagingSenderId: '533186851590',
    projectId: 'siskang-cbf03',
    storageBucket: 'siskang-cbf03.appspot.com',
    androidClientId: '533186851590-43mb32kddkt1nvnnjrroq2dkphrp58a0.apps.googleusercontent.com',
    iosClientId: '533186851590-ka00rtov6iv22vpons332gs4v8rud53t.apps.googleusercontent.com',
    iosBundleId: 'com.pasca.siskangv2',
  );
}
